# Generated by Django 5.1.1 on 2024-10-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Profile',
        ),
    ]
